#!/usr/bin/env bash
# Regenerate the pinned test constraints used by CI (.github/workflows/tests.yaml)
# and by tox's [testenv]. This is what makes the test environment reproducible
# outside of CI (issue #912): everyone installing `.[test]` (or [test,rfdetr]) with
# `-c constraints/test-py313.txt` resolves the exact same dependency versions.
#
# Re-run this whenever pyproject dependencies change (or on a schedule) and commit
# the result. Requires `uv` (https://docs.astral.sh/uv/) and Python 3.13, matching
# the CI matrix.
#
# Usage: scripts/compile_constraints.sh
set -euo pipefail
cd "$(dirname "$0")/.."

PY_VERSION=3.13
OUT=constraints/test-py${PY_VERSION//./}.txt

command -v uv >/dev/null || { echo "error: uv not found (pip install uv)"; exit 1; }

mkdir -p constraints
echo "Compiling ${OUT} for Python ${PY_VERSION} from [test,rfdetr] ..."
# Make the autogenerated banner point back at this script rather than the raw uv command.
export UV_CUSTOM_COMPILE_COMMAND="scripts/compile_constraints.sh"
uv pip compile pyproject.toml \
  --extra test --extra rfdetr \
  --python-version "${PY_VERSION}" \
  --output-file "${OUT}"

echo "Done: ${OUT}"
echo "Constraints cap versions only; extras not installed (wxc, geobenchv2, ...) simply float."
